# Generated by Django 6.0.3 on 2026-04-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_options_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id', '-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
