# Generated by Django 6.0.4 on 2026-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_tasks_users_attachments_comments_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=255, unique=True, verbose_name='Текст комментария'),
        ),
    ]
